// import Navbar from '@/components/Navbar';
// import ServerProtected from '@/components/protect-server/ServerProtected';
import ServerPublic from '@/components/protect-server/ServerPublic';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Ecommerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ServerPublic>{children}</ServerPublic>
    </>
  );
}
