import Footer from '@/components/Footer';
import ServerProtected from '@/components/protect-server/ServerProtected';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Ecommerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ServerProtected>{children}</ServerProtected>
      <Footer />
    </>
  );
}
